@startuml 券売機のオブジェクト図
skinparam classAttributeIconSize 0
hide circle
left to right direction


class  商品の購入{
    商品選択
    金額出力
    おつり出金
    券取得
}

class  管理メニュー{
    売り上げリセット
    商品の価格を変更
    管理メニューを終了
}

class 田中  {
    商品選択 = 特製ラーメン
    金額出力 = 1000円
    金額入金 = 1000円
    おつり出金 = 0円
    券取得 = 食券(特製ラーメン)
}


class 鈴木 {
    商品選択 = 醬油ラーメン
    金額出力 = 780円
    金額入金 = 1000円
    おつり出金 = 220円
    券取得 = 食券(醤油ラーメン)
}

class 伊藤 {
    商品選択 = 塩ラーメン&ご飯
    金額出力 = 1030円
    金額入金 = 1100円
    おつり出金 = 70円
    券取得 = 食券(塩ラーメン)\n　　　　 食券(ご飯)
}

class 管理者 {
    売り上げリセット = リセット
    商品の価格を変更 = ご飯150円→200円
    管理メニューを終了 = 終了
}

商品の購入 --> 田中
商品の購入 --> 鈴木
商品の購入 --> 伊藤
管理メニュー --> 管理者


@enduml
