@startuml 券売機のクラス図
skinparam classAttributeIconSize 0

class 券売機 {
- タイトル画面
---
+ 商品の購入（）:void
+ 管理メニュー（）:void
}

class 商品の購入 {
+ ボタンで商品を選択（）:int
+ 商品の合計金額を出力（）:int
+ 支払いとおつりの出金（）:int
+ 券取得（）:void
}


class 管理メニュー {
+ 売り上げリセット（）:void
+ 商品の価格をリセット（）:void
+ 管理メニューを終了（）:void
}

    券売機 --> 商品の購入
    券売機 --> 管理メニュー


@enduml
