@startuml ドメインモデル図
title ドメインモデル図

rectangle 券売機 { 

rectangle 購入画面{
card 購入
    card 金額
    card 商品
    card 特製ラーメン
    card 塩ラーメン
    card 醤油ラーメン
    card ご飯

購入 --* 商品
購入 --* 金額
商品 --* 特製ラーメン
商品 --* 塩ラーメン
商品 --* 醤油ラーメン
商品 --* ご飯
}

rectangle 管理画面 {
    card 管理メニュー
    card 売上リセット
    card 価格リセット
    card 管理メニュー終了

管理メニュー --* 売上リセット
管理メニュー --* 価格リセット
管理メニュー --* 管理メニュー終了

}
}
@enduml
